### ISSUE TITLE
Default configuration on new project not working

### ISSUE THREAD

**Issue by fedekau** [rmachielse/ember-cli-deploy-chrome-app#6]
Hi ! This just happened to me today, I believe I did set up things correctly, so I guess it is a problem in the addon, here are the details:

In a brand new project with the following versions:

- ember: 2.18.1
- ember-cli-deploy: 1.0.2
- ember-cli-deploy-chrome-app: 0.4.0

Full `package.json`

```js
{
  "name": "ember-chrome-extension-example",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for ember-chrome-extension-example goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "lint:js": "eslint ./*.js app config lib server tests",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.18.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-chrome-app": "^0.4.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-data": "~2.18.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.18.0",
    "ember-welcome-page": "^3.0.0",
    "eslint-plugin-ember": "^5.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  }
}

```

`ember deploy development` blows up with 
```TypeError: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at Promise (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/ember-cli-deploy-chrome-app/index.js:119:26)
    at initializePromise (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/rsvp/dist/rsvp.js:1039:33)
    at Class._ensureOutputPath (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/ember-cli-deploy-chrome-app/index.js:118:16)
    at Class.didBuild (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/ember-cli-deploy-chrome-app/index.js:53:21)
    at Object.fn (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/federico/fedekau/ember-chrome-extension-example/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
Pipeline aborted
```

Looking at the code I decided to add a `distDir` key to the `config/deploy.js` file

```
'chrome-app': {
      distDir: 'chrome-extension'
},
```

After the `ember deploy development`  command is executed the `chrome-extension` folder is created with a `chrome` folder in it but no `zip` is created in the project tree.

**Comment by rmachielse** [comment]
Hi @fedekau 
This addon only handles the creation of a chrome app, you have to add ember-cli-deploy plugins like ember-cli-deploy-build to make sure you have a build in the first place. You’ll probably also need ember-cli-deploy-manifest as well. Can you add those and let me know if that changes anything? I’m using this plugin with ember-cli 2.18 and ember-cli-deploy 1.0 as well.

**Comment by fedekau** [comment]
@rmachielse It seems to work now with those addons. I still don't see the zip file with the extension 🤔 am I missing something else?

**Comment by rmachielse** [comment]
@fedekau you’re only getting a zip if you add the required config for it, see https://github.com/rmachielse/ember-cli-deploy-chrome-app#chrome-web-store-distributed-apps

**Comment by fedekau** [comment]
Ohh, sorry for that @rmachielse, thanks 😄
